// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

// Injectors from wire_build.go:

func InitializeHandlerV0() *HandlerV0 {
	userService := NewUserService()
	handlerV0 := NewHandlerV0(userService)
	return handlerV0
}

func InitializeHandlerV1() *HandlerV1 {
	userService := NewUserService()
	authenticationService := NewAuthenticationService()
	handlerV1Deps := NewHandlerV1Deps(userService, authenticationService)
	handlerV1 := NewHandlerV1(handlerV1Deps)
	return handlerV1
}
